{% set name = "mostlyai" %}
{% set version = "4.6.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mostlyai-{{ version }}.tar.gz
  sha256: 34327ed4ecae1781b98ba4b9760085750538336bfe707e876795378bb455fe6c

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - pydantic >=2.4.2,<3
    - httpx >=0.25.0
    - pandas >=2.0.0
    - pyarrow >=16.0.0
    - smart-open >=6.0.0
    - rich >=13.7.0
    - psutil >=5.9.5
    - requests >=2.31.0
    - typer >=0.9.0
    - semantic_version >=2.10.0
    - gunicorn >=23.0.0
    - environs >=9.5.0
    - schema >=0.7.5
    - python-xxhash >=3.2.0
    - greenlet >=3.1.1
    - pycryptodomex >=3.10.0
    - ipywidgets >=8.1.0
    - python-duckdb >=1.2.1
    - sqlparse >=0.5.3

test:
  imports:
    - mostlyai
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Synthetic Data SDK
  license: Apache-2.0
  license_file: LICENSE
  home: https://github.com/mostly-ai/mostlyai

extra:
  recipe-maintainers:
    - AndreasAlbertQC
